# docker-compose.yml
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: plant-monitoring-timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plant_monitoring
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - verdant-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: plant-monitoring-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - timescaledb
    networks:
      - verdant-network


  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: plant-monitoring-mqtt
    ports:
      - "1883:1883"     # MQTT protocol
      - "9001:9001"     # WebSocket (optional)
    volumes:
      - mosquitto_data:/mosquitto/data:rw
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/log:/mosquitto/log:rw
    networks:
      - verdant-network

volumes:
  timescale_data:
  mosquitto_data:

networks:
  verdant-network:
    driver: bridge

